services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: .
    image: fastapiproj
    depends_on:
      db:
        condition: service_healthy 
    ports:
      - 80:8000
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL=: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINS: ${ACCESS_TOKEN_EXPIRE_MINS}
    command:
      - sh
      - -c
      - alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
